// Generated by scripts/build_timezones.py from timezones.h. Do not edit.
// Same order as kTimezones; codegen checks the counts match.
#pragma once

#include <cstdint>

namespace espn {

// Mirrors ESPHome's time::DSTRule / time::ParsedTimezone field by field
// (type: 0 none, 1 Mm.w.d, 2 Jn, 3 n) without depending on its headers.
struct TzRule {
  int32_t time_seconds;
  uint16_t day;
  uint8_t type;
  uint8_t month;
  uint8_t week;
  uint8_t day_of_week;
};

struct TzParsed {
  int32_t std_offset_seconds;
  int32_t dst_offset_seconds;
  TzRule dst_start;
  TzRule dst_end;
};

constexpr TzParsed kTimezonesParsed[] = {
    {18000, 14400, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // US Eastern: EST5EDT,M3.2.0,M11.1.0
    {21600, 18000, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // US Central: CST6CDT,M3.2.0,M11.1.0
    {25200, 21600, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // US Mountain: MST7MDT,M3.2.0,M11.1.0
    {25200, 0, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}},  // US Arizona: MST7
    {28800, 25200, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // US Pacific: PST8PDT,M3.2.0,M11.1.0
    {32400, 28800, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // US Alaska: AKST9AKDT,M3.2.0,M11.1.0
    {36000, 0, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}},  // US Hawaii: HST10
    {14400, 10800, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // Canada Atlantic: AST4ADT,M3.2.0,M11.1.0
    {12600, 9000, {7200, 0, 1, 3, 2, 0}, {7200, 0, 1, 11, 1, 0}},  // Canada Newfoundland: NST3:30NDT,M3.2.0,M11.1.0
    {21600, 0, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}},  // Mexico City: CST6
    {0, -3600, {3600, 0, 1, 3, 5, 0}, {7200, 0, 1, 10, 5, 0}},  // UK and Ireland: GMT0BST,M3.5.0/1,M10.5.0
    {-3600, -7200, {7200, 0, 1, 3, 5, 0}, {10800, 0, 1, 10, 5, 0}},  // Central Europe: CET-1CEST,M3.5.0,M10.5.0/3
    {-36000, -39600, {7200, 0, 1, 10, 1, 0}, {10800, 0, 1, 4, 1, 0}},  // Australia Eastern: AEST-10AEDT,M10.1.0,M4.1.0/3
    {0, 0, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}},  // UTC: UTC0
};

constexpr size_t kTimezonesParsedCount = sizeof(kTimezonesParsed) / sizeof(kTimezonesParsed[0]);

}  // namespace espn
