#!/usr/bin/env python3
"""Bundle the device web page: team table (from teams.h) + app.js -> bundle.js.

ESPHome embeds a single js_include file, so the team list and the app are
concatenated here. Run after editing firmware/web/app.js or regenerating
components/gameday/teams.h, and commit bundle.js.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEAMS_H = ROOT / "components" / "gameday" / "teams.h"
APP_JS = ROOT / "firmware" / "web" / "app.js"
BUNDLE = ROOT / "firmware" / "web" / "bundle.js"

TEAM_RE = re.compile(r'\{League::(NFL|NCAA),\s*(\d+),\s*"([^"]*)",\s*"([^"]*)",\s*(\d+)\}')


def main():
    rows = []
    for league, tid, abbr, name, _group in TEAM_RE.findall(TEAMS_H.read_text(encoding="utf-8")):
        rows.append(["nfl" if league == "NFL" else "ncaa", int(tid), abbr, name])
    if len(rows) < 100:
        raise SystemExit("teams.h looks truncated")
    header = "// Generated by scripts/build_web.py from teams.h and app.js. Do not edit.\n"
    teams = "const TEAMS=" + json.dumps(rows, separators=(",", ":"), ensure_ascii=False) + ";\n"
    BUNDLE.write_text(header + teams + APP_JS.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
    print(f"wrote {BUNDLE} ({BUNDLE.stat().st_size} bytes, {len(rows)} teams)")


if __name__ == "__main__":
    main()
