#!/usr/bin/env python3
"""Regenerate components/gameday/teams.h from ESPN.

Run this at release time. The header is committed so firmware builds never
need network access.

NFL comes from the league team list. FBS membership is not exposed cleanly
by the teams endpoint (it returns FCS and D3 schools too), so the college
list is collected from a season's worth of FBS scoreboards and filtered by
conference id.
"""

import json
import sys
import urllib.request
from pathlib import Path

SITE = "https://site.api.espn.com/apis/site/v2/sports/football"

# ESPN conference group ids that make up the FBS.
FBS_GROUPS = {
    1: "ACC",
    4: "Big 12",
    5: "Big Ten",
    8: "SEC",
    9: "Pac-12",
    12: "Conference USA",
    15: "MAC",
    17: "Mountain West",
    18: "FBS Independents",
    37: "Sun Belt",
    151: "American",
}

OUT = Path(__file__).resolve().parent.parent / "components" / "gameday" / "teams.h"


# ESPN returns 403 to most unfamiliar agents but accepts ones that start with "curl/".
def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "curl/8.0 gameday-scoreboard"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def nfl_teams():
    data = get(f"{SITE}/nfl/teams?limit=100")
    teams = []
    for entry in data["sports"][0]["leagues"][0]["teams"]:
        t = entry["team"]
        teams.append((0, int(t["id"]), t["abbreviation"], t["displayName"], 0))
    return teams


def ncaa_teams():
    found = {}
    for week in range(1, 16):
        url = f"{SITE}/college-football/scoreboard?groups=80&limit=400&week={week}"
        try:
            data = get(url)
        except Exception as ex:  # a missing week is not fatal
            print(f"week {week}: {ex}", file=sys.stderr)
            continue
        for ev in data.get("events", []):
            for comp in ev["competitions"][0]["competitors"]:
                t = comp["team"]
                conf = int(t.get("conferenceId", 0) or 0)
                if conf not in FBS_GROUPS:
                    continue
                found[int(t["id"])] = (1, int(t["id"]), t["abbreviation"], t["displayName"], conf)
    return list(found.values())


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    nfl = nfl_teams()
    ncaa = ncaa_teams()
    print(f"NFL: {len(nfl)} teams, NCAA FBS: {len(ncaa)} teams")
    if len(nfl) != 32:
        sys.exit("expected 32 NFL teams")
    if len(ncaa) < 120:
        sys.exit("expected at least 120 FBS teams; is it the off season?")

    rows = sorted(nfl, key=lambda r: r[3]) + sorted(ncaa, key=lambda r: r[3])
    lines = [
        "// Generated by scripts/build_teams.py. Do not edit by hand.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace espn {",
        "",
        "enum class League : uint8_t { NFL = 0, NCAA = 1 };",
        "",
        "struct Team {",
        "  League league;",
        "  uint32_t espn_id;",
        "  const char *abbr;",
        "  const char *name;",
        "  uint32_t group;  // conference group id for the college scoreboard, 0 for NFL",
        "};",
        "",
        "constexpr Team kTeams[] = {",
    ]
    for league, tid, abbr, name, group in rows:
        lg = "League::NFL" if league == 0 else "League::NCAA"
        lines.append(f"    {{{lg}, {tid}, {cstr(abbr)}, {cstr(name)}, {group}}},")
    lines += [
        "};",
        "",
        "constexpr size_t kTeamCount = sizeof(kTeams) / sizeof(kTeams[0]);",
        "",
        "}  // namespace espn",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
