#!/usr/bin/env python3
"""Pre-parse the POSIX strings in components/gameday/timezones.h into
components/gameday/timezones_parsed.h.

ESPHome 2026.9 dropped its on-device POSIX parser; the clock takes a
pre-parsed struct instead (time::set_global_tz). This uses the same parser
ESPHome's codegen uses (aioesphomeapi.posix_tz), so run it from an ESPHome
venv and commit the result whenever timezones.h changes.
"""

import re
from pathlib import Path

from aioesphomeapi.posix_tz import parse_posix_tz

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "components" / "gameday" / "timezones.h"
DST = ROOT / "components" / "gameday" / "timezones_parsed.h"
TZ_RE = re.compile(r'\{"([^"]+)",\s*"([^"]+)",\s*"([^"]+)"\}')


def rule(r):
    return f"{{{r.time_seconds}, {r.day}, {int(r.type)}, {r.month}, {r.week}, {r.day_of_week}}}"


def main():
    text = "\n".join(ln for ln in SRC.read_text(encoding="utf-8").splitlines() if not ln.lstrip().startswith("//"))
    rows = TZ_RE.findall(text)
    if not rows:
        raise SystemExit("timezones.h has no entries")
    out = [
        "// Generated by scripts/build_timezones.py from timezones.h. Do not edit.",
        "// Same order as kTimezones; codegen checks the counts match.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace espn {",
        "",
        "// Mirrors ESPHome's time::DSTRule / time::ParsedTimezone field by field",
        "// (type: 0 none, 1 Mm.w.d, 2 Jn, 3 n) without depending on its headers.",
        "struct TzRule {",
        "  int32_t time_seconds;",
        "  uint16_t day;",
        "  uint8_t type;",
        "  uint8_t month;",
        "  uint8_t week;",
        "  uint8_t day_of_week;",
        "};",
        "",
        "struct TzParsed {",
        "  int32_t std_offset_seconds;",
        "  int32_t dst_offset_seconds;",
        "  TzRule dst_start;",
        "  TzRule dst_end;",
        "};",
        "",
        "constexpr TzParsed kTimezonesParsed[] = {",
    ]
    for name, posix, _iana in rows:
        tz = parse_posix_tz(posix)
        out.append(f"    {{{tz.std_offset_seconds}, {tz.dst_offset_seconds}, {rule(tz.dst_start)}, {rule(tz.dst_end)}}},  // {name}: {posix}")
    out += [
        "};",
        "",
        "constexpr size_t kTimezonesParsedCount = sizeof(kTimezonesParsed) / sizeof(kTimezonesParsed[0]);",
        "",
        "}  // namespace espn",
        "",
    ]
    DST.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {DST} ({len(rows)} zones)")


if __name__ == "__main__":
    main()
